name: CI

on:
  push:
    branches: [2.2.x]
  pull_request:

jobs:
  test-deploy:
    name: Test and deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.17]
        os: [ubuntu-latest, macos-latest]
        upload-coverage: [true]
        include:
          - go: 1.17
            os: windows-latest
            upload-coverage: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build for Linux/macOS x86_64
        if: startsWith(matrix.os, 'windows-') != true
        run: |
          go build -trimpath -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/version.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/v2/version.date=`date -u +%FT%TZ`" -o sftpgo
          cd tests/eventsearcher
          go build -trimpath -ldflags "-s -w" -o eventsearcher
          cd -

      - name: Build for macOS arm64
        if: startsWith(matrix.os, 'macos-') == true
        run: CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 SDKROOT=$(xcrun --sdk macosx --show-sdk-path) go build -trimpath -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/version.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/v2/version.date=`date -u +%FT%TZ`" -o sftpgo_arm64

      - name: Build for Windows
        if: startsWith(matrix.os, 'windows-')
        run: |
          $GIT_COMMIT = (git describe --always --dirty) | Out-String
          $DATE_TIME = ([datetime]::Now.ToUniversalTime().toString("yyyy-MM-ddTHH:mm:ssZ")) | Out-String
          $LATEST_TAG = ((git describe --tags $(git rev-list --tags --max-count=1)) | Out-String).Trim()
          $REV_LIST=$LATEST_TAG+"..HEAD"
          $COMMITS_FROM_TAG= ((git rev-list $REV_LIST --count) | Out-String).Trim()
          $FILE_VERSION = $LATEST_TAG.substring(1)  + "." + $COMMITS_FROM_TAG
          go install github.com/tc-hib/go-winres@latest
          go-winres simply --arch amd64 --product-version $LATEST_TAG-dev-$GIT_COMMIT --file-version $FILE_VERSION --file-description "SFTPGo server" --product-name SFTPGo --copyright "AGPL-3.0" --original-filename sftpgo.exe --icon  .\windows-installer\icon.ico
          go build -trimpath -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/version.commit=$GIT_COMMIT -X github.com/drakkan/sftpgo/v2/version.date=$DATE_TIME" -o sftpgo.exe
          cd tests/eventsearcher
          go build -trimpath -ldflags "-s -w" -o eventsearcher.exe
          cd ../..
          mkdir arm64
          $Env:CGO_ENABLED='0'
          $Env:GOOS='windows'
          $Env:GOARCH='arm64'
          go-winres simply --arch arm64 --product-version $LATEST_TAG-dev-$GIT_COMMIT --file-version $FILE_VERSION --file-description "SFTPGo server" --product-name SFTPGo --copyright "AGPL-3.0" --original-filename sftpgo.exe --icon  .\windows-installer\icon.ico
          go build -trimpath -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/version.commit=$GIT_COMMIT -X github.com/drakkan/sftpgo/v2/version.date=$DATE_TIME" -o .\arm64\sftpgo.exe
          mkdir x86
          $Env:GOARCH='386'
          go-winres simply --arch 386 --product-version $LATEST_TAG-dev-$GIT_COMMIT --file-version $FILE_VERSION --file-description "SFTPGo server" --product-name SFTPGo --copyright "AGPL-3.0" --original-filename sftpgo.exe --icon  .\windows-installer\icon.ico
          go build -trimpath -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/version.commit=$GIT_COMMIT -X github.com/drakkan/sftpgo/v2/version.date=$DATE_TIME" -o .\x86\sftpgo.exe
          Remove-Item Env:\CGO_ENABLED
          Remove-Item Env:\GOOS
          Remove-Item Env:\GOARCH

      - name: Run test cases using SQLite provider
        run: go test -v -p 1 -timeout 15m ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        if: ${{ matrix.upload-coverage }}
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

      - name: Run test cases using bolt provider
        run: |
          go test -v -p 1 -timeout 2m ./config -covermode=atomic
          go test -v -p 1 -timeout 5m ./common -covermode=atomic
          go test -v -p 1 -timeout 5m ./httpd -covermode=atomic
          go test -v -p 1 -timeout 8m ./sftpd -covermode=atomic
          go test -v -p 1 -timeout 5m ./ftpd -covermode=atomic
          go test -v -p 1 -timeout 5m ./webdavd -covermode=atomic
          go test -v -p 1 -timeout 2m ./telemetry -covermode=atomic
          go test -v -p 1 -timeout 2m ./mfa -covermode=atomic
        env:
          SFTPGO_DATA_PROVIDER__DRIVER: bolt
          SFTPGO_DATA_PROVIDER__NAME: 'sftpgo_bolt.db'

      - name: Run test cases using memory provider
        run: go test -v -p 1 -timeout 15m ./... -covermode=atomic
        env:
          SFTPGO_DATA_PROVIDER__DRIVER: memory
          SFTPGO_DATA_PROVIDER__NAME: ''

      - name: Prepare build artifact for macOS
        if: startsWith(matrix.os, 'macos-') == true
        run: |
          mkdir -p output/{init,bash_completion,zsh_completion}
          cp sftpgo output/sftpgo_x86_64
          cp sftpgo_arm64 output/
          cp sftpgo.json output/
          cp -r templates output/
          cp -r static output/
          cp -r openapi output/
          cp init/com.github.drakkan.sftpgo.plist output/init/
          ./sftpgo gen completion bash > output/bash_completion/sftpgo
          ./sftpgo gen completion zsh > output/zsh_completion/_sftpgo
          ./sftpgo gen man -d output/man/man1
          gzip output/man/man1/*

      - name: Prepare Windows installer
        if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
        run: |
          Remove-Item -LiteralPath "output" -Force -Recurse -ErrorAction Ignore
          mkdir output
          copy .\sftpgo.exe .\output
          copy .\sftpgo.json .\output
          copy .\sftpgo.db .\output
          copy .\LICENSE .\output\LICENSE.txt
          mkdir output\templates
          xcopy .\templates .\output\templates\ /E
          mkdir output\static
          xcopy .\static .\output\static\ /E
          mkdir output\openapi
          xcopy .\openapi .\output\openapi\ /E
          $LATEST_TAG = ((git describe --tags $(git rev-list --tags --max-count=1)) | Out-String).Trim()
          $REV_LIST=$LATEST_TAG+"..HEAD"
          $COMMITS_FROM_TAG= ((git rev-list $REV_LIST --count) | Out-String).Trim()
          $Env:SFTPGO_ISS_DEV_VERSION = $LATEST_TAG  + "." + $COMMITS_FROM_TAG
          $CERT_PATH=(Get-Location -PSProvider FileSystem).ProviderPath + "\cert.pfx"
          [IO.File]::WriteAllBytes($CERT_PATH,[System.Convert]::FromBase64String($Env:CERT_DATA))
          certutil -f -p "$Env:CERT_PASS" -importpfx MY "$CERT_PATH"
          rm "$CERT_PATH"
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /sm /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /n "Nicola Murino" /d "SFTPGo" .\sftpgo.exe
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /sm /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /n "Nicola Murino" /d "SFTPGo" .\arm64\sftpgo.exe
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /sm /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /n "Nicola Murino" /d "SFTPGo" .\x86\sftpgo.exe
          $INNO_S='/Ssigntool=$qC:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe$q sign /sm /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /n $qNicola Murino$q /d $qSFTPGo$q $f'
          iscc "$INNO_S" .\windows-installer\sftpgo.iss

          rm .\output\sftpgo.exe
          rm .\output\sftpgo.db
          copy .\arm64\sftpgo.exe .\output
          (Get-Content .\output\sftpgo.json).replace('"sqlite"', '"bolt"') | Set-Content .\output\sftpgo.json
          $Env:SFTPGO_DATA_PROVIDER__DRIVER='bolt'
          $Env:SFTPGO_DATA_PROVIDER__NAME='.\output\sftpgo.db'
          .\sftpgo.exe initprovider
          Remove-Item Env:\SFTPGO_DATA_PROVIDER__DRIVER
          Remove-Item Env:\SFTPGO_DATA_PROVIDER__NAME
          $Env:SFTPGO_ISS_ARCH='arm64'
          iscc "$INNO_S" .\windows-installer\sftpgo.iss

          rm .\output\sftpgo.exe
          copy .\x86\sftpgo.exe .\output
          $Env:SFTPGO_ISS_ARCH='x86'
          iscc "$INNO_S" .\windows-installer\sftpgo.iss
          certutil -delstore MY "Nicola Murino"
        env:
          CERT_DATA: ${{ secrets.CERT_DATA }}
          CERT_PASS: ${{ secrets.CERT_PASS }}

      - name: Upload Windows installer x86_64 artifact
        if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo_windows_installer_x86_64
          path: ./sftpgo_windows_x86_64.exe

      - name: Upload Windows installer arm64 artifact
        if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo_windows_installer_arm64
          path: ./sftpgo_windows_arm64.exe

      - name: Upload Windows installer x86 artifact
        if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo_windows_installer_x86
          path: ./sftpgo_windows_x86.exe

      - name: Prepare build artifact for Windows
        if: startsWith(matrix.os, 'windows-')
        run: |
          Remove-Item -LiteralPath "output" -Force -Recurse -ErrorAction Ignore
          mkdir output
          copy .\sftpgo.exe .\output
          mkdir output\arm64
          copy .\arm64\sftpgo.exe .\output\arm64
          mkdir output\x86
          copy .\x86\sftpgo.exe .\output\x86
          copy .\sftpgo.json .\output
          (Get-Content .\output\sftpgo.json).replace('"sqlite"', '"bolt"') | Set-Content .\output\sftpgo.json
          mkdir output\templates
          xcopy .\templates .\output\templates\ /E
          mkdir output\static
          xcopy .\static .\output\static\ /E
          mkdir output\openapi
          xcopy .\openapi .\output\openapi\ /E

      - name: Upload build artifact
        if: startsWith(matrix.os, 'ubuntu-') != true
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo-${{ matrix.os }}-go-${{ matrix.go }}
          path: output

  test-goarch-386:
    name: Run test cases on 32-bit arch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          cd tests/eventsearcher
          go build -trimpath -ldflags "-s -w" -o eventsearcher
          cd -
        env:
          GOARCH: 386

      - name: Run test cases
        run: go test -v -p 1 -timeout 15m ./... -covermode=atomic
        env:
          SFTPGO_DATA_PROVIDER__DRIVER: memory
          SFTPGO_DATA_PROVIDER__NAME: ''
          GOARCH: 386

  test-postgresql-mysql-crdb:
    name: Test with PgSQL/MySQL/Cockroach
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sftpgo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: sftpgo
          MYSQL_USER: sftpgo
          MYSQL_PASSWORD: sftpgo
        options: >-
          --health-cmd "mysqladmin status -h 127.0.0.1 -P 3306 -u root -p$MYSQL_ROOT_PASSWORD"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 6
        ports:
          - 3307:3306

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          cd tests/eventsearcher
          go build -trimpath -ldflags "-s -w" -o eventsearcher
          cd -

      - name: Run tests using PostgreSQL provider
        run: |
          go test -v -p 1 -timeout 15m ./... -covermode=atomic
        env:
          SFTPGO_DATA_PROVIDER__DRIVER: postgresql
          SFTPGO_DATA_PROVIDER__NAME: sftpgo
          SFTPGO_DATA_PROVIDER__HOST: localhost
          SFTPGO_DATA_PROVIDER__PORT: 5432
          SFTPGO_DATA_PROVIDER__USERNAME: postgres
          SFTPGO_DATA_PROVIDER__PASSWORD: postgres

      - name: Run tests using MySQL provider
        run: |
          go test -v -p 1 -timeout 15m ./... -covermode=atomic
        env:
          SFTPGO_DATA_PROVIDER__DRIVER: mysql
          SFTPGO_DATA_PROVIDER__NAME: sftpgo
          SFTPGO_DATA_PROVIDER__HOST: localhost
          SFTPGO_DATA_PROVIDER__PORT: 3307
          SFTPGO_DATA_PROVIDER__USERNAME: sftpgo
          SFTPGO_DATA_PROVIDER__PASSWORD: sftpgo

      - name: Run tests using CockroachDB provider
        run: |
          docker run --rm --name crdb --health-cmd "curl -I http://127.0.0.1:8080" --health-interval 10s --health-timeout 5s --health-retries 6 -p 26257:26257 -d cockroachdb/cockroach:latest start-single-node --insecure --listen-addr 0.0.0.0:26257
          docker exec crdb cockroach sql --insecure -e 'create database "sftpgo"'
          go test -v -p 1 -timeout 15m ./... -covermode=atomic
          docker stop crdb
        env:
          SFTPGO_DATA_PROVIDER__DRIVER: cockroachdb
          SFTPGO_DATA_PROVIDER__NAME: sftpgo
          SFTPGO_DATA_PROVIDER__HOST: localhost
          SFTPGO_DATA_PROVIDER__PORT: 26257
          SFTPGO_DATA_PROVIDER__USERNAME: root
          SFTPGO_DATA_PROVIDER__PASSWORD:

  build-linux-packages:
    name: Build Linux packages
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - arch: amd64
            go: 1.17
            go-arch: amd64
          - arch: aarch64
            distro: ubuntu18.04
            go: latest
            go-arch: arm64
          - arch: ppc64le
            distro: ubuntu18.04
            go: latest
            go-arch: ppc64le
          - arch: armv7
            distro: ubuntu18.04
            go: latest
            go-arch: arm7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        if: ${{ matrix.arch == 'amd64' }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build on amd64
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          go build -trimpath -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/version.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/v2/version.date=`date -u +%FT%TZ`" -o sftpgo
          mkdir -p output/{init,bash_completion,zsh_completion}
          cp sftpgo.json output/
          cp -r templates output/
          cp -r static output/
          cp -r openapi output/
          cp init/sftpgo.service output/init/
          ./sftpgo gen completion bash > output/bash_completion/sftpgo
          ./sftpgo gen completion zsh > output/zsh_completion/_sftpgo
          ./sftpgo gen man -d output/man/man1
          gzip output/man/man1/*
          cp sftpgo output/

      - uses: uraimo/run-on-arch-action@v2.1.1
        if: ${{ matrix.arch != 'amd64' }}
        name: Build for ${{ matrix.arch }}
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          setup: |
            mkdir -p "${PWD}/output"
          dockerRunArgs: |
            --volume "${PWD}/output:/output"
          shell: /bin/bash
          install: |
            apt-get update -q -y
            apt-get install -q -y curl gcc git
            if [ ${{ matrix.go }} == 'latest' ]
            then
              GO_VERSION=$(curl -L https://go.dev/VERSION?m=text)
            else
              GO_VERSION=${{ matrix.go }}
            fi
            GO_DOWNLOAD_ARCH=${{ matrix.go-arch }}
            if [ ${{ matrix.arch}} == 'armv7' ]
            then
              GO_DOWNLOAD_ARCH=armv6l
            fi
            curl --retry 5 --retry-delay 2 --connect-timeout 10 -o go.tar.gz -L https://go.dev/dl/${GO_VERSION}.linux-${GO_DOWNLOAD_ARCH}.tar.gz
            tar -C /usr/local -xzf go.tar.gz
          run: |
            export PATH=$PATH:/usr/local/go/bin
            if [ ${{ matrix.arch}} == 'armv7' ]
            then
              export GOARM=7
            fi
            go build -trimpath -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/version.commit=`git describe --always --dirty` -X github.com/drakkan/sftpgo/v2/version.date=`date -u +%FT%TZ`" -o sftpgo
            mkdir -p output/{init,bash_completion,zsh_completion}
            cp sftpgo.json output/
            cp -r templates output/
            cp -r static output/
            cp -r openapi output/
            cp init/sftpgo.service output/init/
            ./sftpgo gen completion bash > output/bash_completion/sftpgo
            ./sftpgo gen completion zsh > output/zsh_completion/_sftpgo
            ./sftpgo gen man -d output/man/man1
            gzip output/man/man1/*
            cp sftpgo output/

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo-linux-${{ matrix.arch }}-go-${{ matrix.go }}
          path: output

      - name: Build Packages
        id: build_linux_pkgs
        run: |
          export NFPM_ARCH=${{ matrix.go-arch }}
          cd pkgs
          ./build.sh
          PKG_VERSION=$(cat dist/version)
          echo "::set-output name=pkg-version::${PKG_VERSION}"

      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo-${{ steps.build_linux_pkgs.outputs.pkg-version }}-${{ matrix.go-arch }}-deb
          path: pkgs/dist/deb/*

      - name: Upload RPM Package
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo-${{ steps.build_linux_pkgs.outputs.pkg-version }}-${{ matrix.go-arch }}-rpm
          path: pkgs/dist/rpm/*

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
